<?php

return [
    [
        'name' => 'Ichiban',
        'email' => 'Ichiban@gmail.com',
        'password' => '12345',
        'address' => 'via Ichiban',
        'vat_number' => '12345678910',
        'city' => 'Verona',
        'image' => 'logo_01.jpg',
        'id_category' => 1,
    ],
    [
        'name' => 'Yoshinoya',
        'email' => 'Yoshinoya@gmail.com',
        'password' => '12345',
        'address' => 'via Yoshinoya',
        'vat_number' => '12345678910',
        'city' => 'Reggio Calabria',
        'image' => 'logo_02.png',
        'id_category' => 1,
    ],
    [
        'name' => 'Sorbillo',
        'email' => 'Sorbillo@gmail.com',
        'password' => '12345',
        'address' => 'via Sorbillo',
        'vat_number' => '12345678910',
        'city' => 'Genova',
        'image' => 'logo_03.png',
        'id_category' => 2,
    ],
    [
        'name' => 'Spontini',
        'email' => 'Spontini@gmail.com',
        'password' => '12345',
        'address' => 'via Spontini',
        'vat_number' => '12345678910',
        'city' => 'Verona',
        'image' => 'logo_04.png',
        'id_category' => 2,
    ],
    [
        'name' => 'Flower Burger',
        'email' => 'Flower@gmail.com',
        'password' => '12345',
        'address' => 'via Flower',
        'vat_number' => '12345678910',
        'city' => 'Verona',
        'image' => 'logo_05.png',
        'id_category' => 3,
    ],
    [
        'name' => 'Five Guys',
        'email' => 'Fg@gmail.com',
        'password' => '12345',
        'address' => 'via Five',
        'vat_number' => '12345678910',
        'city' => 'Verona',
        'image' => 'logo_06.png',
        'id_category' => 3,
    ],
    [
        'name' => 'Eataly',
        'email' => 'Eataly@gmail.com',
        'password' => '12345',
        'address' => 'via Eataly',
        'vat_number' => '12345678910',
        'city' => 'Ancona',
        'image' => 'logo_07.jpg',
        'id_category' => 6,
    ],
    [
        'name' => 'La Piadineria',
        'email' => 'La Piadineria@gmail.com',
        'password' => '12345',
        'address' => 'via La Piadineria',
        'vat_number' => '12345678910',
        'city' => 'Verona',
        'image' => 'logo_08.jpg',
        'id_category' => 6,
    ],
    [
        'name' => 'RoadHouse',
        'email' => 'RoadHouse@gmail.com',
        'password' => '12345',
        'address' => 'via RoadHouse',
        'vat_number' => '12345678910',
        'city' => 'Verona',
        'image' => 'logo_09.webp',
        'id_category' => 5,
    ],
    [
        'name' => 'Old Wild West',
        'email' => 'OWW@gmail.com',
        'password' => '12345',
        'address' => 'via Old Wild West',
        'vat_number' => '12345678910',
        'city' => 'Ancona',
        'image' => 'logo_10.jpg',
        'id_category' => 5,
    ],
    [
        'name' => 'Panda Express',
        'email' => 'Panda@gmail.com',
        'password' => '12345',
        'address' => 'via dei Panda',
        'vat_number' => '12345678910',
        'city' => 'Verona',
        'image' => 'logo_11.png',
        'id_category' => 4,
    ],
    [
        'name' => 'Wok to Walk',
        'email' => 'wok@gmail.com',
        'password' => '12345',
        'address' => 'via dei Wok',
        'vat_number' => '12345678910',
        'city' => 'Verona',
        'image' => 'logo_12.png',
        'id_category' => 4,
    ],
    [
        'name' => 'Taco Bell',
        'email' => 'Tacoooos@gmail.com',
        'password' => '12345',
        'address' => 'via Bell',
        'vat_number' => '12345678910',
        'city' => 'Ancona',
        'image' => 'logo_13.webp',
        'id_category' => 7,
    ],
    [
        'name' => 'Calavera',
        'email' => 'Calavera@gmail.com',
        'password' => '12345',
        'address' => 'via Calavera',
        'vat_number' => '12345678910',
        'city' => 'Verona',
        'image' => 'logo_14.png',
        'id_category' => 7,
    ],
    [
        'name' => 'Pescaria',
        'email' => 'Pescaria@gmail.com',
        'password' => '12345',
        'address' => 'via Pescaria',
        'vat_number' => '12345678910',
        'city' => 'Verona',
        'image' => 'logo_15.jpg',
        'id_category' => 8,
    ],
    [
        'name' => 'NordSee',
        'email' => 'NordSee@gmail.com',
        'password' => '12345',
        'address' => 'via NordSee',
        'vat_number' => '12345678910',
        'city' => 'Verona',
        'image' => 'logo_16.png',
        'id_category' => 8,
    ],

];
