<?php
return [
    [
        'name' => 'Ichiban',
        'email' => 'Ichiban@gmail.com',
        'password' => '12345',
        'address' => 'Via Mazzini',
        'vat_number' => '12345678910',
        'city' => 'Verona',
        'image' => 'logo_01.jpg',
        'id_category' => 1,
    ],
    [
        'name' => 'Yoshinoya',
        'email' => 'Yoshinoya@gmail.com',
        'password' => '12345',
        'address' => 'Corso Garibaldi',
        'vat_number' => '12345678321',
        'city' => 'Reggio Calabria',
        'image' => 'logo_02.png',
        'id_category' => 1,
    ],
    [
        'name' => 'Sorbillo',
        'email' => 'Sorbillo@gmail.com',
        'password' => '12345',
        'address' => 'Via di Prè',
        'vat_number' => '12345678999',
        'city' => 'Genova',
        'image' => 'logo_03.png',
        'id_category' => 2,
    ],
    [
        'name' => 'Spontini',
        'email' => 'Spontini@gmail.com',
        'password' => '12345',
        'address' => 'Via di Sottoriva',
        'vat_number' => '12345678070',
        'city' => 'Verona',
        'image' => 'logo_04.png',
        'id_category' => 2,
    ],
    [
        'name' => 'Flower Burger',
        'email' => 'Flower@gmail.com',
        'password' => '12345',
        'address' => 'Via Cappello',
        'vat_number' => '12345678222',
        'city' => 'Verona',
        'image' => 'logo_05.png',
        'id_category' => 3,
    ],
    [
        'name' => 'Five Guys',
        'email' => 'Fg@gmail.com',
        'password' => '12345',
        'address' => 'Via Giordano Bruno',
        'vat_number' => '12345679010',
        'city' => 'Ancona',
        'image' => 'logo_06.png',
        'id_category' => 3,
    ],
    [
        'name' => 'Eataly',
        'email' => 'Eataly@gmail.com',
        'password' => '12345',
        'address' => 'Via Umberto Saracini',
        'vat_number' => '12345678910',
        'city' => 'Ancona',
        'image' => 'logo_07.jpg',
        'id_category' => 6,
    ],
    [
        'name' => 'La Piadineria',
        'email' => 'La Piadineria@gmail.com',
        'password' => '12345',
        'address' => 'Corso Porta Nuova',
        'vat_number' => '12345678888',
        'city' => 'Verona',
        'image' => 'logo_08.jpg',
        'id_category' => 6,
    ],
    [
        'name' => 'RoadHouse',
        'email' => 'RoadHouse@gmail.com',
        'password' => '12345',
        'address' => 'Lungomare Falcomatà',
        'vat_number' => '12345673232',
        'city' => 'Reggio Calabria',
        'image' => 'logo_09.webp',
        'id_category' => 5,
    ],
    [
        'name' => 'Old Wild West',
        'email' => 'OWW@gmail.com',
        'password' => '12345',
        'address' => 'Via Scrima',
        'vat_number' => '12345678019',
        'city' => 'Ancona',
        'image' => 'logo_10.jpg',
        'id_category' => 5,
    ],
    [
        'name' => 'Panda Express',
        'email' => 'Panda@gmail.com',
        'password' => '12345',
        'address' => 'via Leoni',
        'vat_number' => '12345678121',
        'city' => 'Verona',
        'image' => 'logo_11.png',
        'id_category' => 4,
    ],
    [
        'name' => 'Wok to Walk',
        'email' => 'wok@gmail.com',
        'password' => '12345',
        'address' => 'Via Fieschi',
        'vat_number' => '12345671212',
        'city' => 'Genova',
        'image' => 'logo_12.png',
        'id_category' => 4,
    ],
    [
        'name' => 'Taco Bell',
        'email' => 'Tacoooos@gmail.com',
        'password' => '12345',
        'address' => 'via Belli',
        'vat_number' => '12345672020',
        'city' => 'Ancona',
        'image' => 'logo_13.webp',
        'id_category' => 7,
    ],
    [
        'name' => 'Calavera',
        'email' => 'Calavera@gmail.com',
        'password' => '12345',
        'address' => 'Via Carlo Cattaneo',
        'vat_number' => '12345678910',
        'city' => 'Verona',
        'image' => 'logo_14.png',
        'id_category' => 7,
    ],
    [
        'name' => 'Pescaria',
        'email' => 'Pescaria@gmail.com',
        'password' => '12345',
        'address' => 'Piazza Dante',
        'vat_number' => '12345388910',
        'city' => 'Genova',
        'image' => 'logo_15.jpg',
        'id_category' => 8,
    ],
    [
        'name' => 'NordSee',
        'email' => 'NordSee@gmail.com',
        'password' => '12345',
        'address' => 'Via Scrima',
        'vat_number' => '12345678910',
        'city' => 'Ancona',
        'image' => 'logo_16.png',
        'id_category' => 8,
    ],
    [
        'name' => 'Ootoya',
        'email' => 'Ootoya@gmail.com',
        'password' => '12345',
        'address' => 'Via Antonio Cimino',
        'vat_number' => '21345678901',
        'city' => 'Reggio Calabria',
        'image' => 'logo_17.jpg',
        'id_category' => 1,
    ],
    [
        'name' => 'Ruth Chris',
        'email' => 'Ruth Chris@gmail.com',
        'password' => '12345',
        'address' => 'Via Pesaro',
        'vat_number' => '12545678933',
        'city' => 'Ancona',
        'image' => 'logo_18.png',
        'id_category' => 5,
    ],
    [
        'name' => 'Mulan',
        'email' => 'Mulan@gmail.com',
        'password' => '12345',
        'address' => 'Via 25 Aprile',
        'vat_number' => '12345678932',
        'city' => 'Genova',
        'image' => 'logo_19.png',
        'id_category' => 4,
    ],
    [
        'name' => 'Burger King',
        'email' => 'BurgerKing@gmail.com',
        'password' => '12345',
        'address' => 'Via Tommaso Campanella',
        'vat_number' => '12345678332',
        'city' => 'Reggio Calabria',
        'image' => 'logo_20.webp',
        'id_category' => 3,
    ],
    [
        'name' => 'Rosso Pomodoro',
        'email' => 'rossopomodoro@gmail.com',
        'password' => '12345',
        'address' => 'Via alla Porta degli Arch',
        'vat_number' => '12345678256',
        'city' => 'Genova',
        'image' => 'logo_21.jpg',
        'id_category' => 2,
    ],
    [
        'name' => 'Bubba Gump',
        'email' => 'Bubbagump@gmail.com',
        'password' => '12345',
        'address' => 'Via Roma',
        'vat_number' => '12345670004',
        'city' => 'Genova',
        'image' => 'logo_22.jpg',
        'id_category' => 8,
    ],
    [
        'name' => 'El Moccolo',
        'email' => 'Elmoccolo@gmail.com',
        'password' => '12345',
        'address' => 'Via Capodistria',
        'vat_number' => '12345670003',
        'city' => 'Ancona',
        'image' => 'logo_23.png',
        'id_category' => 7,
    ],
    [
        'name' => 'Vapiano',
        'email' => 'Vapiano@gmail.com',
        'password' => '12345',
        'address' => 'Via Crocefisso',
        'vat_number' => '12345670002',
        'city' => 'Reggio Calabria',
        'image' => 'logo_24.jpg',
        'id_category' => 6,
    ],
    [
        'name' => 'Wendy’xs',
        'email' => 'Wendy’s@gmail.com',
        'password' => '12345',
        'address' => 'Piazza Castello',
        'vat_number' => '12345670001',
        'city' => 'Reggio Calabria',
        'image' => 'logo_25.png',
        'id_category' => 3,
    ],
    [
        'name' => 'A Tutto Pesce',
        'email' => 'atuttopesce@gmail.com',
        'password' => '12345',
        'address' => 'Stradone Porta Palio',
        'vat_number' => '12345670022',
        'city' => 'Verona',
        'image' => 'logo_26.jpg',
        'id_category' => 8,
    ],
    [
        'name' => 'Manzo Criminale',
        'email' => 'manzocriminale@gmail.com',
        'password' => '12345',
        'address' => 'Via 25 Aprile',
        'vat_number' => '12345670038',
        'city' => 'Genova',
        'image' => 'logo_27.jpg',
        'id_category' => 5,
    ],
    [
        'name' => 'Dao',
        'email' => 'dao@gmail.com',
        'password' => '12345',
        'address' => 'Via 25 Aprile',
        'vat_number' => '12345670066',
        'city' => 'Reggio Calabria',
        'image' => 'logo_28.jpg',
        'id_category' => 4,
    ],
    [
        'name' => 'White Castle',
        'email' => 'whitecastle@gmail.com',
        'password' => '12345',
        'address' => 'Via Primo Maggio',
        'vat_number' => '12345670055',
        'city' => 'Reggio Calabria',
        'image' => 'logo_29.png',
        'id_category' => 3,
    ],
    [
        'name' => 'Sagami',
        'email' => 'Sagami@gmail.com',
        'password' => '12345',
        'address' => 'Via Gabriele Annunzio',
        'vat_number' => '12345670045',
        'city' => 'Genova',
        'image' => 'logo_30.jpg',
        'id_category' => 1,
    ],
    [
        'name' => 'Trapizzino',
        'email' => 'trapizzino@gmail.com',
        'password' => '12345',
        'address' => 'Via Giuseppe Ragnini',
        'vat_number' => '12345670555',
        'city' => 'Ancona',
        'image' => 'logo_31.jpg',
        'id_category' => 6,
    ],
    [
        'name' => 'Alice Pizza',
        'email' => 'alicepizza@gmail.com',
        'password' => '12345',
        'address' => 'Via Roma',
        'vat_number' => '12345670455',
        'city' => 'Genova',
        'image' => 'logo_32.jpg',
        'id_category' => 2,
    ],

];
